[build]
  command = "yarn install && npx expo export --platform web"
  publish = "dist/server"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/_expo/*"
  to = "/_expo/:splat"
  status = 200